### ISSUE TITLE
bugs list

### ISSUE THREAD

**Issue by Gamer4378** [CarsCupcake/SkyblockRemake#36]
Bugs i have found soo far (end and hub):
1. skyblock menu (nether star) disappears when shift - click (hub)
2. voidgloom slayer t1 - t4 teleport after shot by a terminator (in hub)
3. skyblock menu doesn't work in hub (when right click)
4. "go back" in every menu doesn't work
5. Mining and farming collection menus are missing some glass
6. can't use terminator in creative
7. zelot and zelot bruisers name tags don't despawn when killed
8.  new zelots/voidgloom sometimes don't show their name tags

**Comment by CarsCupcake** [comment]
nametags dont despawn? i never used armorstand for the nametags so this should be a client issue then

**Comment by PanKaJxD69** [comment]
How ur plugin working mine's not even showing in plugin folder

**Comment by Nooobdgod** [comment]
Best plugin ever well-done carscupcake nice work
