### ISSUE TITLE
Multi Version support

### ISSUE THREAD

**Issue by schooldanlp6** [CarsCupcake/SkyblockRemake#42]
Could it be possible to develop this plugin for a deprecated version of mc like 1.8.9 as this is the best version for stuff like that. Koji had legacy and not legacy support (i switched to this plugin as this is way better tho)

I have a good reason liking the older software as microsoft isnt updating the clients for them which means more privacy.

Thanks to acknowledge my feedback :)

To end of my post with a question which other mods did you use is everything made from scratch

**Comment by CarsCupcake** [comment]
im sorry but i have currently no plan on downgrading to 1.8.9, in fact i have the idea to upgrade to 1.19 because real hypixel is doing that too

**Comment by CarsCupcake** [comment]
and i coded this entierly from scratch, use fawe for quick pasting of schematics and the drag code was enspired by atlas. I also copied a class called "ReflectionUtils" as this is just a usefull utils class
