### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [CarsCupcake/SkyblockRemake#45]
Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

https://github.com/CarsCupcake/SkyblockRemake/blob/683723c51df47a4a4715d56b7f8033ef7e9927e9/src/main/java/me/CarsCupcake/SkyblockRemake/abilities/WearableHelmets.java#L25

**Comment by CarsCupcake** [comment]
this type of inventory is no longer in use and is just there bcs i never changed it (view my gui system)
